### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by d0uub** [niw/AlpacaChat#2]
sorry i am beginner of swift and see this error:

> swift build -c release
Building for production...
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1150:15: error: unknown type name '__m128'
static inline __m128 __sse_f16x4_load(ggml_fp16_t *x) {
              ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1158:12: error: call to undeclared function '_mm_loadu_ps'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    return _mm_loadu_ps(tmp);
           ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1161:54: error: unknown type name '__m128'
static inline void __sse_f16x4_store(ggml_fp16_t *x, __m128 y) {
                                                     ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1164:5: error: call to undeclared function '_mm_storeu_ps'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    _mm_storeu_ps(arr, y);
    ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1229:5: error: use of undeclared identifier '__m128'
    GGML_F32_VEC sum[GGML_F32_ARR] = { GGML_F32_VEC_ZERO };
    ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1135:29: note: expanded from macro 'GGML_F32_VEC'
#define GGML_F32_VEC        GGML_F32x4
                            ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1106:28: note: expanded from macro 'GGML_F32x4'
#define GGML_F32x4         __m128
                           ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1231:5: error: use of undeclared identifier '__m128'
    GGML_F32_VEC ax[GGML_F32_ARR];
    ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1135:29: note: expanded from macro 'GGML_F32_VEC'
#define GGML_F32_VEC        GGML_F32x4
                            ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1106:28: note: expanded from macro 'GGML_F32x4'
#define GGML_F32x4         __m128
                           ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1232:5: error: use of undeclared identifier '__m128'
    GGML_F32_VEC ay[GGML_F32_ARR];
    ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1135:29: note: expanded from macro 'GGML_F32_VEC'
#define GGML_F32_VEC        GGML_F32x4
                            ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1106:28: note: expanded from macro 'GGML_F32x4'
#define GGML_F32x4         __m128
                           ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1236:13: error: use of undeclared identifier 'ax'
            ax[j] = GGML_F32_VEC_LOAD(x + i + j*GGML_F32_EPR);
            ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1236:21: error: call to undeclared function '_mm_loadu_ps'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
            ax[j] = GGML_F32_VEC_LOAD(x + i + j*GGML_F32_EPR);
                    ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1138:29: note: expanded from macro 'GGML_F32_VEC_LOAD'
#define GGML_F32_VEC_LOAD   GGML_F32x4_LOAD
                            ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1109:28: note: expanded from macro 'GGML_F32x4_LOAD'
#define GGML_F32x4_LOAD    _mm_loadu_ps
                           ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1237:13: error: use of undeclared identifier 'ay'
            ay[j] = GGML_F32_VEC_LOAD(y + i + j*GGML_F32_EPR);
            ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1239:13: error: use of undeclared identifier 'sum'; did you mean 'sumf'?
            sum[j] = GGML_F32_VEC_FMA(sum[j], ax[j], ay[j]);
            ^~~
            sumf
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1224:16: note: 'sumf' declared here
    ggml_float sumf = 0.0;
               ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1239:16: error: subscripted value is not an array, pointer, or vector
            sum[j] = GGML_F32_VEC_FMA(sum[j], ax[j], ay[j]);
            ~~~^~
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1239:22: error: call to undeclared function '_mm_add_ps'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
            sum[j] = GGML_F32_VEC_FMA(sum[j], ax[j], ay[j]);
                     ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1140:29: note: expanded from macro 'GGML_F32_VEC_FMA'
#define GGML_F32_VEC_FMA    GGML_F32x4_FMA
                            ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1115:37: note: expanded from macro 'GGML_F32x4_FMA'
    #define GGML_F32x4_FMA(a, b, c) _mm_add_ps(_mm_mul_ps(b, c), a)
                                    ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1239:22: error: call to undeclared function '_mm_mul_ps'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1140:29: note: expanded from macro 'GGML_F32_VEC_FMA'
#define GGML_F32_VEC_FMA    GGML_F32x4_FMA
                            ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1115:48: note: expanded from macro 'GGML_F32x4_FMA'
    #define GGML_F32x4_FMA(a, b, c) _mm_add_ps(_mm_mul_ps(b, c), a)
                                               ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1239:47: error: use of undeclared identifier 'ax'
            sum[j] = GGML_F32_VEC_FMA(sum[j], ax[j], ay[j]);
                                              ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1140:29: note: expanded from macro 'GGML_F32_VEC_FMA'
#define GGML_F32_VEC_FMA    GGML_F32x4_FMA
                            ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1239:54: error: use of undeclared identifier 'ay'
            sum[j] = GGML_F32_VEC_FMA(sum[j], ax[j], ay[j]);
                                                     ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1140:29: note: expanded from macro 'GGML_F32_VEC_FMA'
#define GGML_F32_VEC_FMA    GGML_F32x4_FMA
                            ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1239:39: error: use of undeclared identifier 'sum'; did you mean 'sumf'?
            sum[j] = GGML_F32_VEC_FMA(sum[j], ax[j], ay[j]);
                                      ^~~
                                      sumf
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1140:29: note: expanded from macro 'GGML_F32_VEC_FMA'
#define GGML_F32_VEC_FMA    GGML_F32x4_FMA
                            ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1115:66: note: expanded from macro 'GGML_F32x4_FMA'
    #define GGML_F32x4_FMA(a, b, c) _mm_add_ps(_mm_mul_ps(b, c), a)
                                                                 ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1224:16: note: 'sumf' declared here
    ggml_float sumf = 0.0;
               ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1239:42: error: subscripted value is not an array, pointer, or vector
            sum[j] = GGML_F32_VEC_FMA(sum[j], ax[j], ay[j]);
                                      ~~~^~
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1140:29: note: expanded from macro 'GGML_F32_VEC_FMA'
#define GGML_F32_VEC_FMA    GGML_F32x4_FMA
                            ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1115:66: note: expanded from macro 'GGML_F32x4_FMA'
    #define GGML_F32x4_FMA(a, b, c) _mm_add_ps(_mm_mul_ps(b, c), a)
                                                                 ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1244:31: error: use of undeclared identifier 'sum'; did you mean 'sumf'?
    GGML_F32_VEC_REDUCE(sumf, sum);
                              ^~~
                              sumf
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1143:29: note: expanded from macro 'GGML_F32_VEC_REDUCE'
#define GGML_F32_VEC_REDUCE GGML_F32x4_REDUCE
                            ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1122:9: note: expanded from macro 'GGML_F32x4_REDUCE'
        x[2*i] = _mm_add_ps(x[2*i], x[2*i+1]);                    \
        ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1224:16: note: 'sumf' declared here
    ggml_float sumf = 0.0;
               ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
[0/4] Compiling alpaca.cpp chat.cpp

**Comment by niw** [comment]
Ah, there is a unexpected `return` in the code, I forgot to remove. Fixed on the latest tip branch. Please pull it and try again.

**Comment by d0uub** [comment]
it's better but still error in other code:

$ swift build -c release
Fetching https://github.com/apple/swift-argument-parser
Fetched https://github.com/apple/swift-argument-parser (1.60s)
Computing version for https://github.com/apple/swift-argument-parser
Computed https://github.com/apple/swift-argument-parser at 1.2.2 (1.60s)
Creating working copy for https://github.com/apple/swift-argument-parser
Working copy of https://github.com/apple/swift-argument-parser resolved at 1.2.2
Building for production...
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1150:15: error: unknown type name '__m128'
static inline __m128 __sse_f16x4_load(ggml_fp16_t *x) {
              ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1158:12: error: call to undeclared function '_mm_loadu_ps'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    return _mm_loadu_ps(tmp);
           ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1161:54: error: unknown type name '__m128'
static inline void __sse_f16x4_store(ggml_fp16_t *x, __m128 y) {
                                                     ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1164:5: error: call to undeclared function '_mm_storeu_ps'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    _mm_storeu_ps(arr, y);
    ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1229:5: error: use of undeclared identifier '__m128'
    GGML_F32_VEC sum[GGML_F32_ARR] = { GGML_F32_VEC_ZERO };
    ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1135:29: note: expanded from macro 'GGML_F32_VEC'
#define GGML_F32_VEC        GGML_F32x4
                            ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1106:28: note: expanded from macro 'GGML_F32x4'
#define GGML_F32x4         __m128
                           ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1231:5: error: use of undeclared identifier '__m128'
    GGML_F32_VEC ax[GGML_F32_ARR];
    ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1135:29: note: expanded from macro 'GGML_F32_VEC'
#define GGML_F32_VEC        GGML_F32x4
                            ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1106:28: note: expanded from macro 'GGML_F32x4'
#define GGML_F32x4         __m128
                           ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1232:5: error: use of undeclared identifier '__m128'
    GGML_F32_VEC ay[GGML_F32_ARR];
    ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1135:29: note: expanded from macro 'GGML_F32_VEC'
#define GGML_F32_VEC        GGML_F32x4
                            ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1106:28: note: expanded from macro 'GGML_F32x4'
#define GGML_F32x4         __m128
                           ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1236:13: error: use of undeclared identifier 'ax'
            ax[j] = GGML_F32_VEC_LOAD(x + i + j*GGML_F32_EPR);
            ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1236:21: error: call to undeclared function '_mm_loadu_ps'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
            ax[j] = GGML_F32_VEC_LOAD(x + i + j*GGML_F32_EPR);
                    ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1138:29: note: expanded from macro 'GGML_F32_VEC_LOAD'
#define GGML_F32_VEC_LOAD   GGML_F32x4_LOAD
                            ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1109:28: note: expanded from macro 'GGML_F32x4_LOAD'
#define GGML_F32x4_LOAD    _mm_loadu_ps
                           ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1237:13: error: use of undeclared identifier 'ay'
            ay[j] = GGML_F32_VEC_LOAD(y + i + j*GGML_F32_EPR);
            ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1239:13: error: use of undeclared identifier 'sum'; did you mean 'sumf'?
            sum[j] = GGML_F32_VEC_FMA(sum[j], ax[j], ay[j]);
            ^~~
            sumf
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1224:16: note: 'sumf' declared here
    ggml_float sumf = 0.0;
               ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1239:16: error: subscripted value is not an array, pointer, or vector
            sum[j] = GGML_F32_VEC_FMA(sum[j], ax[j], ay[j]);
            ~~~^~
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1239:22: error: call to undeclared function '_mm_add_ps'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
            sum[j] = GGML_F32_VEC_FMA(sum[j], ax[j], ay[j]);
                     ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1140:29: note: expanded from macro 'GGML_F32_VEC_FMA'
#define GGML_F32_VEC_FMA    GGML_F32x4_FMA
                            ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1115:37: note: expanded from macro 'GGML_F32x4_FMA'
    #define GGML_F32x4_FMA(a, b, c) _mm_add_ps(_mm_mul_ps(b, c), a)
                                    ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1239:22: error: call to undeclared function '_mm_mul_ps'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1140:29: note: expanded from macro 'GGML_F32_VEC_FMA'
#define GGML_F32_VEC_FMA    GGML_F32x4_FMA
                            ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1115:48: note: expanded from macro 'GGML_F32x4_FMA'
    #define GGML_F32x4_FMA(a, b, c) _mm_add_ps(_mm_mul_ps(b, c), a)
                                               ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1239:47: error: use of undeclared identifier 'ax'
            sum[j] = GGML_F32_VEC_FMA(sum[j], ax[j], ay[j]);
                                              ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1140:29: note: expanded from macro 'GGML_F32_VEC_FMA'
#define GGML_F32_VEC_FMA    GGML_F32x4_FMA
                            ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1239:54: error: use of undeclared identifier 'ay'
            sum[j] = GGML_F32_VEC_FMA(sum[j], ax[j], ay[j]);
                                                     ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1140:29: note: expanded from macro 'GGML_F32_VEC_FMA'
#define GGML_F32_VEC_FMA    GGML_F32x4_FMA
                            ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1239:39: error: use of undeclared identifier 'sum'; did you mean 'sumf'?
            sum[j] = GGML_F32_VEC_FMA(sum[j], ax[j], ay[j]);
                                      ^~~
                                      sumf
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1140:29: note: expanded from macro 'GGML_F32_VEC_FMA'
#define GGML_F32_VEC_FMA    GGML_F32x4_FMA
                            ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1115:66: note: expanded from macro 'GGML_F32x4_FMA'
    #define GGML_F32x4_FMA(a, b, c) _mm_add_ps(_mm_mul_ps(b, c), a)
                                                                 ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1224:16: note: 'sumf' declared here
    ggml_float sumf = 0.0;
               ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1239:42: error: subscripted value is not an array, pointer, or vector
            sum[j] = GGML_F32_VEC_FMA(sum[j], ax[j], ay[j]);
                                      ~~~^~
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1140:29: note: expanded from macro 'GGML_F32_VEC_FMA'
#define GGML_F32_VEC_FMA    GGML_F32x4_FMA
                            ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1115:66: note: expanded from macro 'GGML_F32x4_FMA'
    #define GGML_F32x4_FMA(a, b, c) _mm_add_ps(_mm_mul_ps(b, c), a)
                                                                 ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1244:31: error: use of undeclared identifier 'sum'; did you mean 'sumf'?
    GGML_F32_VEC_REDUCE(sumf, sum);
                              ^~~
                              sumf
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1143:29: note: expanded from macro 'GGML_F32_VEC_REDUCE'
#define GGML_F32_VEC_REDUCE GGML_F32x4_REDUCE
                            ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1122:9: note: expanded from macro 'GGML_F32x4_REDUCE'
        x[2*i] = _mm_add_ps(x[2*i], x[2*i+1]);                    \
        ^
/Users/administrator/AlpacaChat/Sources/alpaca.cpp/ggml.c:1224:16: note: 'sumf' declared here
    ggml_float sumf = 0.0;
               ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
[1/6] Compiling alpaca.cpp utils.cpp

**Comment by niw** [comment]
What is your output of `swift --version` and `clang --version` and `xcodebuild -version`?

**Comment by d0uub** [comment]
$ swift --version
swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
Target: x86_64-apple-macosx13.0

$ clang --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: x86_64-apple-darwin22.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

$ xcodebuild -version
Xcode 14.3
Build version 14E222b

**Comment by niw** [comment]
Ah, you're using Intel Mac. I haven’t tested this code on Intel Mac, which obviously doesn’t have ARM SIMD.
I no longer have Intel Mac handy, so it may take a while to test this with x64 cross compiling.
You can build this without error on Apple Silicon Mac.

**Comment by d0uub** [comment]
Ic.. let me try on Silicon Mac, thanks

**Comment by niw** [comment]
Actaully it's easy, [adding missing include](https://github.com/niw/AlpacaChat/commit/cef17bef60e9e110e53456f38482bdc966fda2e6) is needed. Try [`x86_64_sse` branch](https://github.com/niw/AlpacaChat/tree/wip/x86_64_sse) I just created.
